apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlog
  namespace: crossbell
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: xlog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xlog
    spec:
      enableServiceLinks: false
      containers:
        - image: $IMAGE_TAG_RELEASE
          imagePullPolicy: Always
          name: xlog
          command: ["npm", "run", "start"]
          envFrom:
            - secretRef:
                name: xlog
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: '200Mi'
              cpu: '150m'
            limits:
              memory: '500Mi'
              cpu: '500m'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 20
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
