apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: xlog
  namespace: crossbell
spec:
  maxReplicas: 8
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xlog
  targetCPUUtilizationPercentage: 70
