# Remember to add it in env.production because it is the nextjs project
apiVersion: v1
stringData:
  NEXT_PUBLIC_APP_NAME: xlog
  NEXT_PUBLIC_OUR_DOMAIN: xlog.app
  NEXT_PUBLIC_DISCORD_LINK: "https://discord.gg/9XscSqJEq4"
  NEXT_PUBLIC_GITHUB_LINK: "https://github.com/Crossbell-Box/xlog"
  NEXT_PUBLIC_CSB_IO: ""
  NEXT_PUBLIC_CSB_SCAN: "https://scan.crossbell.io"
  REDIS_URL: ${REDIS_URL}
kind: Secret
metadata:
  name: xlog
  namespace: crossbell
type: Opaque
