apiVersion: v1
kind: Service
metadata:
  name: xlog-lb
  namespace: crossbell
spec:
  type: LoadBalancer
  selector:
    app: xlog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
