name = "r2"
main = "src/index.ts"
compatibility_date = "2022-05-14"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'proselog'
preview_bucket_name ='proselog-dev'

# secrets
# API_TOKEN
[env.development.vars]
ENCRYPT_SECRET="uIeqyCW1E5PbK2ztsc+UXcPwsZ0L/Z4k08ArOSaKpHHFViRbdnFJcQ=="

# Why do I need to set it again? Cloudflare?
[[env.development.r2_buckets]]
binding = 'BUCKET'
bucket_name = 'proselog'
preview_bucket_name ='proselog-dev'